\begin{thebibliography}{7}

% this bibliography is generated by unsrtdin.bst [8.2] from 2005-12-21

\providecommand{\url}[1]{\texttt{#1}}
\expandafter\ifx\csname urlstyle\endcsname\relax
  \providecommand{\doi}[1]{doi: #1}\else
  \providecommand{\doi}{doi: \begingroup \urlstyle{rm}\Url}\fi

\bibitem[1]{UeberDLR}
\textsc{DLR}:
\newblock \emph{http://www.dlr.de/dlr/desktopdefault.aspx/tabid-10443/637\_read-251/\#/gallery/8570}.
\newblock 2015

\bibitem[2]{Turbofan}
\textsc{Aainsqatsi, K}.:
\newblock \emph{https://commons.wikimedia.org/wiki/File:Turbofan\_operation\_\%28lbp\%29.png}.
\newblock 2008
  

\bibitem[3]{SplinesInet}
\textsc{Demidov, Evgeny}:
\newblock \emph{ibiblio.org/e-notes/Splines/Intro.htm}.
\newblock 2015

\bibitem[4]{PieglTiller1997}
\textsc{Wayne~Tiller, Les~P.}:
\newblock \emph{The NURBS Book}.
\newblock Springer Verlag, 1997

\bibitem[5]{NRUBSSite}
\textsc{McNeel}:
\newblock \emph{http://wiki.mcneel.com/de/rhino/nurbs}.
\newblock 1997-2016

\bibitem[6]{CADFormate}
\textsc{Bergholz, Eric}:
\newblock \emph{http://www.laserscanning-europe.com/de/news/uebersicht-von-cad-datenformaten}.
\newblock 2010

\end{thebibliography}
